# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ToHNOR
                                 A QGIS plugin
 Realiza a conversão de altitude geométrica para altitude normal associada ao SGB
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-26
        copyright            : (C) 2023 by Engenharia Cartográfica e de Agrimensura - PIBIT 2022 - IFG
        email                : joao.paulo@ifg.edu.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ToHNOR class from file ToHNOR.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .to_HNOR import ToHNOR
    return ToHNOR(iface)
